spring.application.name=resumeanalyzer

spring.datasource.url=jdbc:postgresql://localhost:5432/resumeanalyzer
spring.datasource.username=postgres
spring.datasource.password=Nimpostgre*3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true