spring.application.name=resumeanalyzer

spring.datasource.url=jdbc:postgresql://ep-soft-rice-aoym8u4b.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_gcx42XNIlhsn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true